# Generated by Django 5.2.6 on 2025-09-08 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('price', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('clothing', 'Clothing'), ('footwear', 'Footwear'), ('bag', 'Bag'), ('equipment', 'Equipment'), ('merchandise', 'Merchandise')])),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
